language: ruby
rvm: 2.4.1
cache: bundler
script: bundle exec rake test
addons:
  postgresql: "9.6"
before_script:
  - sudo apt-get install postgresql-server-dev-9.6
  - git clone https://github.com/HypoPG/hypopg.git
  - cd hypopg
  - git checkout 1.1.1
  - make
  - sudo make install
  - psql -c 'create database dexter_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
